---
- name: DOCKER
  hosts: testserver
  become: true
  become_user: root
  tasks:
  - name: Install Docker
    yum: name=docker state=present
  - name: Make sure docker runs
    service: name=docker state=started enabled=yes
