---
- name: PUPPET
  hosts: testserver
  become: true
  become_user: root
  tasks:
  - name: Download rpm
    get_url:
      url: https://yum.puppet.com/puppet7-release-el-8.noarch.rpm
      dest: /tmp/package.rpm
  - name: Install package
    yum:
      name: /tmp/package.rpm
      state: present
  - name: Install puppet agent
    yum: name=puppet state=present
  - name: Make sure puppet runs
    service: name=puppet state=started enabled=yes

